name: testRigor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          # Trigger the TestRigor retest
          curl -X POST \
            -H 'Content-type: application/json' \
            -H 'auth-token: d011c630-6f44-4513-b7d3-39da38e53024' \
            --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
            https://api.testrigor.com/api/v1/apps/kWpvzjxn5tYgSZfSG/retest

          sleep 10

          # Poll for the test status
          while true; do
            echo " "
            echo "==================================="
            echo " Checking TestRigor retest"
            echo "==================================="
            response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/kWpvzjxn5tYgSZfSG/status' \
              -H 'auth-token: d011c630-6f44-4513-b7d3-39da38e53024' \
              -H 'Accept: application/json')
            code=$(echo "$response" | grep HTTP | awk '{print $2}')
            body=$(echo "$response" | sed -n '/{/,/}/p')
            echo "Status code: $code"
            echo "Response: $body"

            case $code in
              4*|5*)
                echo "Error calling API"
                exit 1
                ;;
              200)
                echo "Test finished successfully"
                exit 0
                ;;
              227|228)
                echo "Test is not finished yet"
                ;;
              230)
                echo "Test finished but failed"
                exit 1
                ;;
              *)
                echo "Unknown status"
                exit 1
                ;;
            esac
            sleep 10
          done
